fix gsap animation browser compatibility issues
omsimos/omsimos pull request #20
Opened 2023-09-10 13:57 UTC by hyamero

2023-10-13 07:28 UTC, joshxfi commented
routing to `services` or `contact` then routing to `projects` causes it to initialize the loader (which causes black screen for a few seconds)

2023-10-13 07:32 UTC, joshxfi requested changes
routing to `services` or `contact` then routing to `projects` causes it to initialize the loader (which causes black screen for a few seconds)

the initial loader should only trigger on first load & not per route

2023-10-22 13:27 UTC, hyamero commented
> routing to `services` or `contact` then routing to `projects` causes it to initialize the loader (which causes black screen for a few seconds)
> 
> the initial loader should only trigger on first load & not per route

Prevented loader re-initialization when routing by unmounting `Loader` component when animation completes: b63f62f

2023-10-22 13:51 UTC, joshxfi approved these changes

2023-10-22 13:53 UTC, merged